### ISSUE TITLE
Hidden sections where @NTBonds are defined hide the output NTBonds

### ISSUE THREAD

**Issue by dmetivie** [disberd/PlutoExtras.jl#30]
When I create a section with all my @bind @NTBonds etc, I typically want to hide it, but it seems to hide also the nice looking side panel. 
Note that if I hide just the bond cell (not the section), this works as intended, displaying the output.
Is it a bug, or am I (again!) missing something?

**Comment by disberd** [comment]
I assume you are talking about *hiding* from the ExtendedTableOfContents.

If this is the case, I added a function for this specifically in version 0.7.7
https://github.com/disberd/PlutoExtras.jl/blob/85ea50d3ea8249acc933ab29fb04d14f482fba56/src/extended_toc.jl#L1018-L1062

The way you use it is that you simply call it on the output like so:
```julia
BondTable([bonds...]) |> show_output_when_hidden
```

This will make sure that when your notebook is hiding cells the output will still be displayed (for the cell that has `show_output_when_hidden`.)
At the moment the code will hide the cell input if the ToC is set to hide *hidden* heading, **even if the cell itself is not below a hidden section**.
I am gonna fix this in the rewrite of the package but it's not a big issue for the moment as you are anyhow likely gonna put this cell inside a hidden section and you'll have to show hidden section to modify the cell's content.

I know documentation is currently very poor but I plan on also improving this with the rewrite of the package (Unfortunately this still depends on a rewrite of PlutoDevMacros so it will not happen before weeks from now)

**Comment by disberd** [comment]
@dmetivie here is a clearer video example

https://github.com/disberd/PlutoExtras.jl/assets/12846528/c7906f31-dc0c-4ff7-b006-27b91117ff5f

**Comment by dmetivie** [comment]
Thanks ! You thought of every thing yet!
