### ISSUE TITLE
Method Overwriting Conflict

### ISSUE THREAD

**Issue by stefanbringuier** [disberd/PlutoExtras.jl#34]
Seeing a warning and an error in my notebooks that use `PlutoExtras`. Seems to prevent precompiling which may leading to potential issues in notebook functionality?

```
WARNING: Method definition @bind(LineNumberNode, Module, Any, Any) in module PlutoExtras at /home/stefanbringuier/.julia/packages/PlutoExtras/WGpIT/src/editable.jl:8 overwritten at /home/stefanbringuier/.julia/packages/PlutoExtras/WGpIT/src/stringonenter.jl:8.
ERROR: Method overwriting is not permitted during Module precompilation. Use __precompile__(false) to opt-out of precompilation.
```

## Environment
- Julia Version: 1.10.2
- OS: Ubuntu 22.04.4 LTS
- Pluto.jl version:  0.19.40
- PlutoExtras version: 0.7.8

**Comment by disberd** [comment]
Yeah I have always disliked the automatic insertion of `@bind` definition in the notebook file. I'll try to see if it's feasible to release a patch version removing all those definition and maybe try to see if it's possible to add an option in Pluto to opt out of this.

**Comment by stefanbringuier** [comment]
>Is there a specific reason you are still using 0.7.8 and/or can you try with the latest version?
No, it is just part of my template notebook I use. Let me try latest version.

**Comment by stefanbringuier** [comment]
Bumping version solves issue. Thanks.
